### ISSUE TITLE
ModuleInfo compiler parse fails

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/cactus-build#25]
Our new module info compiler reports the error below when building the hadoop doubly-shaded jar. The problem seems to be due to the `exports to` clause I added in kivakit-resource's module-info.java:  `exports com.telenav.kivakit.resource.internal.lexakai to kivakit.network.http`. The `to` clause has been left commented out in the `feature/relocate-lexakai-annotations` branch because it causes this failure.

```
[WARNING] Begin compile of synthetic module-info.java
[INFO] ModuleInfo Compiler: /var/folders/rm/1qd3sg1n6gx12kbf39xgp73w0000gn/T/minfo-synthl6p82ep9-1/src/module-info.java:92: warning: [module] module not found: kivakit.network.http
[INFO]         kivakit.network.http;
[INFO]                        ^
[INFO] /var/folders/rm/1qd3sg1n6gx12kbf39xgp73w0000gn/T/minfo-synthl6p82ep9-1/src/module-info.java:92: warning: [module] module not found: kivakit.network.http
[INFO]         kivakit.network.http;
```

**Comment by timboudreau** [comment]
I'll take a look at it.

Probably it needs to see if the "to" clause is to a module it is already subsuming and omit it.

Although, the compiler shouldn't object to `exports somepackage to module.ive.never.heard.of` because that's legal.

**Comment by timboudreau** [comment]
This bug is not in a cactus project.
