### ISSUE TITLE
KivaKit PR build failed

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/cactus-build#27]
There's nothing wrong with the branch, as you can see here: https://github.com/Telenav/kivakit/actions. But the pull request to develop fails: https://github.com/Telenav/kivakit/runs/7791514261?check_suite_focus=true

```
[1](https://github.com/Telenav/kivakit/runs/7791514261?check_suite_focus=true#step:33:1)
Run cd $GITHUB_WORKSPACE/telenav-build/$PROJECT && git checkout $GITHUB_SHA
[12](https://github.com/Telenav/kivakit/runs/7791514261?check_suite_focus=true#step:33:13)
fatal: reference is not a tree: df51dba14f3440c8ef0ae0631a56326fdd061b79
[13](https://github.com/Telenav/kivakit/runs/7791514261?check_suite_focus=true#step:33:14)
Error: Process completed with exit code 128.
```

**Comment by jonathanl-telenav** [comment]
After pushing the relevant `telenav-build` branch, the PR build still fails, but the error had a little more information:

```
Run cd $GITHUB_WORKSPACE/telenav-build/$PROJECT && git checkout $GITHUB_SHA
[2](https://github.com/Telenav/kivakit/runs/7791704738?check_suite_focus=true#step:33:2)
  cd $GITHUB_WORKSPACE/telenav-build/$PROJECT && git checkout $GITHUB_SHA
[3](https://github.com/Telenav/kivakit/runs/7791704738?check_suite_focus=true#step:33:3)
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
[4](https://github.com/Telenav/kivakit/runs/7791704738?check_suite_focus=true#step:33:4)
  env:
[5](https://github.com/Telenav/kivakit/runs/7791704738?check_suite_focus=true#step:33:5)
    CACTUS_VERSION: 1.5.21
[6](https://github.com/Telenav/kivakit/runs/7791704738?check_suite_focus=true#step:33:6)
    PROJECT: kivakit
[7](https://github.com/Telenav/kivakit/runs/7791704738?check_suite_focus=true#step:33:7)
    WHEN: 1660236252
[8](https://github.com/Telenav/kivakit/runs/7791704738?check_suite_focus=true#step:33:8)
    MAVEN_REPO: /tmp/mr-1660236252
[9](https://github.com/Telenav/kivakit/runs/7791704738?check_suite_focus=true#step:33:9)
    TARGET_BRANCH: feature/relocate-lexakai-annotations
[10](https://github.com/Telenav/kivakit/runs/7791704738?check_suite_focus=true#step:33:10)
    BASE_BRANCH: develop
[11](https://github.com/Telenav/kivakit/runs/7791704738?check_suite_focus=true#step:33:11)
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.4-8/x64
[12](https://github.com/Telenav/kivakit/runs/7791704738?check_suite_focus=true#step:33:13)
fatal: reference is not a tree: df51dba14f3440c8ef0ae0631a56326fdd061b79
[13](https://github.com/Telenav/kivakit/runs/7791704738?check_suite_focus=true#step:33:14)
Error: Process completed with exit code 128.

**Comment by jonathanl-telenav** [comment]
A strange thing: the same branch builds in some repositories, but not others. For example, the kivakit repository (above) fails. But kivakit-extensions PR build succeeds. Maybe this info can help diagnose.

**Comment by timboudreau** [comment]
Were any of the branches created before we updated the github actions yml's, and not updated with the latest version?

**Comment by timboudreau** [comment]
Okay, the difference in input is:

#### Succeeded - Triggered By Push

```
GITHUB_REF_TYPE=branch
GITHUB_REF=refs/heads/feature/relocate-lexakai-annotations GITHUB_SHA=e44d3e5cb5ca562326304e2d137bae916496f382 
GITHUB_BASE_REF= 
GITHUB_REF_NAME=feature/relocate-lexakai-annotations
```

#### Failed - Triggered By Pull Request

```
GITHUB_REF_TYPE=branch
GITHUB_REF=refs/pull/134/merge
GITHUB_SHA=df51dba14f3440c8ef0ae0631a56326fdd061b79
GITHUB_BASE_REF=develop
GITHUB_REF_NAME=134/merge
```

Now here's the weird thing:  How is it that the *Ensure Merge Commit Is Available Locally* step succeeds (which should pull down the merge commit with the right SHA so it's available locally) - has it changed on the remote since the PR was launched?

```
Run cd $GITHUB_WORKSPACE/telenav-build/$PROJECT && git fetch origin $GITHUB_REF
From https://github.com/Telenav/kivakit
 * branch                refs/pull/[13]
```

If I run it locally now, it fails:

```
git fetch origin refs/pull/134/merge
fatal: couldn't find remote ref refs/pull/134/merge
```

so whatever `refs/pull/134/merge` was, it's gone from the server now (was the PR merged and the branch deleted?).

**Comment by timboudreau** [comment]
Hang on, I was thinking this was the pr in cactus, not kivakit, that was where the failure was.

**Comment by timboudreau** [comment]
Hmm, an alternative way to get the content of the pull request would be, e.g.:

```
git pull --rebase origin refs/pull/134/merge
```

which would have fewer problems, but it would mean if the pull request is against an older version of develop, we're generating a *new* merge commit against its current contents.  Have to think through whether that's an actual problem - it probably isn't for proving whether the changes are good, but it is for repeatability.

**Comment by timboudreau** [comment]
Okay, attempting a fix with [changing the way we compute the target to check out for pull requests](https://github.com/Telenav/telenav-github/commit/25bb5f08838e7114f20803b3d9aefb7c0f4a3802) - I'll push through some whitespace change to force a PR build and see what happens.

**Comment by timboudreau** [comment]
Okay, I think this is fixed - both of these builds are past the point of failure:

 * https://github.com/Telenav/kivakit/runs/7795252220?check_suite_focus=true
 * https://github.com/Telenav/kivakit/runs/7795252542?check_suite_focus=true
 
 This is using the `pull --rebase` approach for the case of PRs.
