### ISSUE TITLE
cactus-development-preparation fails

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/cactus-build#30]
all repositories give this error:

```
[INFO] Skipping CheckoutMojo mojo per policy last-containing-goal
```

**Comment by jonathanl-telenav** [comment]
the same problem occurs with `cactus-push-all-submodules`

**Comment by timboudreau** [comment]
The message above should occur on every project but the first or the last, and it is simply informing you that the project it's currently being invoked against is not the one it is targeting (you wouldn't want to run 'git push' once for each project in the same checkout).

Is there something here that is actually not working, or this is just about the fact that the info message appears?

**Comment by jonathanl-telenav** [comment]
It does not work. I just thought that message might have something to do with it.

**Comment by jonathanl-telenav** [comment]
I don't understand. I ran it again and it worked this time....

**Comment by timboudreau** [comment]
Okay, well, if it happens again, try capturing a log.

Or maybe the scrips should all set of MAVEN_OPTS to make maven log to a file in /tmp and emit the name in case of failure.

**Comment by timboudreau** [comment]
Here's a rough script that would capture maven output to a file *without suppressing stdout and stderr*.

The only downside is stderr and stdout get combined, to suppress the `SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"` warning (there is a logger binding, but it only appears once in Maven's classloader).

So, we could wrap all of our scripts in something like this (might also be useful for `release.sh`) to make them "quiet" without sending all of the diagnostics needed to debug anything into a black hole.

```sh
#!/bin/sh

CACTUS_LOG_LEVEL="${CACTUS_LOG_LEVEL:-info}"
TEMP="${TMPDIR:-/tmp}"
LOG_FILE=$TEMP/cactus-$(date '+%s')-$(basename $0).log

mvn \
  -Dorg.slf4j.simpleLogger.logFile=${LOG_FILE} \
  -Dorg.slf4j.simpleLogger.defaultLogLevel=${CACTUS_LOG_LEVEL} \
  -Dorg.slf4j.simpleLogger.cacheOutputStream=false $@ 2>&1 | grep -v "SLF4J: "


EXIT_CODE=$?
LAST_LOG_LINK=$TEMP/cactus-last.log

rm -f $LAST_LOG_LINK
ln -s $LOG_FILE $LAST_LOG_LINK

if [ $EXIT_CODE -ne 0 ]; then
  echo "Maven execution failed with exit code ${EXIT_CODE}" 1>&2
  echo "A complete log file is in ${LOG_FILE}"  1>&2
  echo "The last cactus log is always linked as cactus-last.log in the system temp folder $TEMP" 1>&2
fi

exit $EXIT_CODE
```

**Comment by jonathanl-telenav** [comment]
yeah, I think that is a good idea.

**Comment by jonathanl-telenav** [comment]
I am adding a function to bin/telenav-library-functions that does this:

```
maven()
{
    local arguments=("$@")

    local log_file
    local log_level
    local temporary_folder
    local exit_code
    local last_log_link

    log_level="${MAVEN_LOG_LEVEL:-info}"
    temporary_folder="${TMPDIR:-/tmp}"
    log_file=$temporary_folder/maven-$(date '+%s')-$(basename "$0").log

    mvn \
      -Dorg.slf4j.simpleLogger.logFile="${log_file}" \
      -Dorg.slf4j.simpleLogger.defaultLogLevel="${log_level}" \
      -Dorg.slf4j.simpleLogger.cacheOutputStream=false \
      "${arguments[*]}" || exit 1 2>&1 | grep -v "SLF4J: "

    exit_code=$?
    last_log_link=$temporary_folder/maven-last.log

    rm -f "$last_log_link"
    ln -s "$log_file" "$last_log_link"

    if [ $exit_code -ne 0 ]; then
      echo "Maven execution failed with exit code ${exit_code}" 1>&2
      echo "A complete log file is in ${log_file}" 1>&2
      echo "The last maven log is always linked as maven-last.log in the system temp folder $temporary_folder" 1>&2
      exit $exit_code
    fi
}

**Comment by jonathanl-telenav** [comment]
found the problem. this is fixed now.
