### ISSUE TITLE
cactus pull request create fails

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/cactus-build#34]
```
[ERROR] Failed to execute goal com.telenav.cactus:cactus-maven-plugin:1.5.23:git-pull-request (default-cli) on project telenav-build: com.telenav.cactus.cli.ProcessFailedException: gh pr create --head feature/maven-logging --base develop --title blah --body blah (in /Users/jonathan/Workspaces/telenav-build/cactus) exited 1
[ERROR] pull request create failed: GraphQL error: No commits between develop and feature/maven-logging

**Comment by jonathanl-telenav** [comment]
some branches may not have any changes and that is okay. not sure which branch caused this, so if possible it would be nice to give that information in the error

**Comment by jonathanl-telenav** [comment]
this link might help:

https://github.com/octokit/octokit.net/issues/879

**Comment by jonathanl-telenav** [comment]
blocks our hoped-for dev process

**Comment by timboudreau** [comment]
More like dreaded, unproductive dev process.

I just pushed a change to prune checkouts from the set if the local head matches or is the ancestor of the remote head.

**Comment by timboudreau** [comment]
(wasn't intending to close - test it)

**Comment by jonathanl-telenav** [comment]
if you really don't want to participate in code reviews, we can make an exception just for you

**Comment by timboudreau** [comment]
I am fine with code reviews.  I am not fine with having my hands tied when I am trying to fix something like the build actions, where you have to debug something by repeatedly pushing changes and reading the output, when doing that via pull requests turns it from a process that takes an hour or two into one that takes several days.

**Comment by timboudreau** [comment]
Anyway, try the fix and see if it solves your problem, and if so, close.

**Comment by timboudreau** [comment]
Marking this as closed.  Reopen if there's a problem the next time you use it.
