### ISSUE TITLE
authentication failing

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/cactus-build#38]
this maven command (created by the telenav-pull-request script) doesn't work as expected:

```
mvn -Dcactus.scope=all -Dcactus.authentication-token="xxxxxxxx" -Dcactus.title="FOO" -Dcactus.to-branch=develop -Dcactus.from-branch="bugfix/pr-list-does-not-take-head-argument" -Dcactus.body="BAR" -Dcactus.reviewers=rodherz,sunshine-syz,timboudreau,wenjuanj,jonathanl-telenav,haifeng-z com.telenav.cactus:cactus-maven-plugin:1.5.24:git-pull-request validate
```

the auth token in the command line is definitely correct (created a new one just to be sure), and the build error is:

```
[ERROR] Failed to execute goal com.telenav.cactus:cactus-maven-plugin:1.5.24:git-pull-request (default-cli) on project telenav-build: com.telenav.cactus.cli.ProcessFailedException: gh pr list --base develop --json url,title,state,mergeable,body,number,headRefName,baseRefName (in /Users/jonathan/Workspaces/telenav-build/cactus) exited 1
[ERROR] HTTP 401: Bad credentials (https://api.github.com/graphql)
[ERROR] hint: try authenticating with `gh auth login`
```

**Comment by timboudreau** [comment]
Hmm.  For all of the ones I've created with it, I used the env var CACTUS_GITHUB_PERSONAL_ACCESS_TOKEN_FILE that points to a file with the PAT in it on disk.  That works fine.

Maybe just print out what it's trying to send and see if it matches what it's supposed to be?

**Comment by timboudreau** [comment]
The property name is wrong in your attempt.  It's `cactus.github-personal-access-token`.
