### ISSUE TITLE
cactus-development-preparation does not switch root branch

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/cactus-build#47]
With feature/testing checked out, execute "cactus-development-preparation". Expect all branches including the root (telenav-build) project to switch to develop. Instead, only the children switch:

<img width="277" alt="Screen Shot 2022-08-24 at 3 03 17 PM" src="https://user-images.githubusercontent.com/15021216/186523068-0e82eb80-5bd4-46e7-89c3-da4998e201ce.png">

**Comment by jonathanl-telenav** [comment]
This can also be reproduced by switching the root to feature/testing and then use cactus-development-preparation.

**Comment by timboudreau** [comment]
This is fixed in the newly released 1.5.26.
