### ISSUE TITLE
ProjectsGeneratorTest fails

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/cactus-build#51]
Not really sure why this failed the second time I ran it, but not the first...
```
[ERROR]   ProjectsGeneratorTest.testAutomergeTagsGeneratedByAutoMergeTagMojoWithAutopush:128->_testAutomergeTagsGeneratedByAutoMergeTagMojoWithAutopush:907 Commit failed ==> expected: <true> but was: <false>
[ERROR]   ProjectsGeneratorTest.testAutomergeTagsGeneratedByAutoMergeTagMojoWithExplictPush:136->_testAutomergeTagsGeneratedByAutoMergeTagMojoWithExplictPush:994 Commit failed ==> expected: <true> but was: <false>
[ERROR]   ProjectsGeneratorTest.testAutomergeTagsGeneratedByCommitMojo:121->_testAutomergeTagsGeneratedByCommitMojo:829 Commit did not happen in com.starwarsl79nrx5hzt.wookies:wookies-fur in /var/folders/rm/1qd3sg1n6gx12kbf39xgp73w0000gn/T/RepositoriesGenerator-l79nrx5h-lqpwbe/workspace-clone-1/wookies/anatomy/external/fur ==> expected: not equal but was: <a469e19ff6ff1eb6c80efeab8f913ae73740a4d2>
[ERROR]   ProjectsGeneratorTest.testBranchesArePickedUp:95->_testBranchesArePickedUp:570 expected: <features/stuff> but was: <develop>
[ERROR]   ProjectsGeneratorTest.testCommitMojoWillNotPushIfConflict:101->_testCommitMojoWillNotPushIfConflict:686 Repo status should not be dirty ==> expected: <false> but was: <true>
[ERROR]   ProjectsGeneratorTest.testPushAndPullWithCactus:69->_testPushAndPullWithCactus:255 Commit failed ==> expected: <true> but was: <false>
[ERROR]   ProjectsGeneratorTest.testPushAndPullWithSeparateCommitAndPushUsingCactusAllProjectFamiliesScope:108->_testPushAndPullWithSeparateCommitAndPushUsingCactusAllProjectFamiliesScope:340 Repo should not have untracked files ==> expected: <false> but was: <true>
[ERROR]   ProjectsGeneratorTest.testPushAndPullWithSeparateCommitAndPushUsingCactusFamilyScope:76->_testPushAndPullWithSeparateCommitAndPushUsingCactusFamilyScope:159 Commit failed ==> expected: <true> but was: <false>
[ERROR]   ProjectsGeneratorTest.testPushJustThisReallyPushesJustThis:89->_testPushJustThisReallyPushesJustThis:436 Repo status should not be dirty ==> expected: <false> but was: <true>
[ERROR]   ProjectsGeneratorTest.testSimpleBumpProjectVersion:115->_testSimpleBumpProjectVersion:756 expected: <true> but was: <false>
[INFO]

**Comment by timboudreau** [comment]
Not at the computer at the moment, but I'd guess it's encountering output from a previous run, or random dir name isn't really random, or something like that.

If it always passes after a clean build, it will be something like that.

**Comment by timboudreau** [comment]
Hmm, one other possibility is that something in your ~/.gitconfig is making git behave in a way the test doesn't expect.

I took care of a few such cases week before last, but there might be some non-obvious ones. There doesn't seem to be a way to tell git to use a different (or no) git config file other than setting HOME for the process, which is not really a great idea.

Could you paste your git config here? I doubt this will be the culprit, but it would be good to rule it out.

**Comment by jonathanl-telenav** [comment]
```
[user]
	name = jonathanl-telenav
	email = jonathanl@telenav.com
	password = *****
[core]
	autocrlf = input
[init]
	defaultBranch = master
[http]
	postBuffer = 64000000
[core]
    packedGitLimit = 512m
    packedGitWindowSize = 512m
[pack]
    deltaCacheSize = 2047m
    packSizeLimit = 2047m
    windowMemory = 2047m
[credential "https://dev.azure.com"]
	useHttpPath = true
[credential "https://github.com"]
	helper =
	helper = !/usr/local/bin/gh auth git-credential

**Comment by jonathanl-telenav** [comment]
there are failures on kivakit-extensions build (as stated already). these are from a clean build and they are BLOCKERS.

**Comment by timboudreau** [comment]
Well, one difference is the setting of `init.defaultBranch` (my .gitconfig sets it to `main`).  I don't *think* there are any tests relying on the default branch having a specific name, since the repos are created passing an explicit branch, but for good measure, I've added setting that in GitCommand.

And seeing if I can reproduce any of this.

When you say *the second time I ran it* - ran it *how*?  Via running `mvn install`, via the maven surefire single test target, or via IntelliJ making wild guesses about what "run this test" means?

**Comment by timboudreau** [comment]
Could you

 - Do a pull of cactus
 - Run `mvn clean install` so tests have run once
 - Then cd into `cactus-tests` and run

```
mvn \
  --no-transfer-progress \
  --batch-mode \
  -Dcactus.test.debug=true \
  -Dcactus.test.slf4j.debug=true \
  -Dtest=com.telenav.cactus.test.project.generator.ProjectsGeneratorTest \
  surefire:test 2>&1 | tee -a /tmp/cactus-tests.log
```

and, if it fails, attach `/tmp/cactus-tests.log` here?

`-Dcactus.test.debug=true` ensures all output from the *tests* running Maven gets captured on stdout, and ` -Dcactus.test.slf4j.debug=true` ensures that it is logging at debug level, so we can see what it's trying to do when the failure occurs.

**Comment by jonathanl-telenav** [comment]
is there a way that you can specify a .gitconfig so the tests don't depend on someone's individual config?

**Comment by jonathanl-telenav** [comment]
it succeeded.

**Comment by jonathanl-telenav** [comment]
after the successful build, I built it again and it worked, so perhaps something was lodged in my maven repo or some other config thing... we can close this and reopen if it happens again

**Comment by timboudreau** [comment]
> is there a way that you can specify a .gitconfig so the tests don't depend on someone's individual config?

No, I looked into that.  You can override individual properties on the command line, but the only way to do it for everything is to change the value of `HOME` for the process, which could have all sorts of other side-effects.
