### ISSUE TITLE
attempt to release lexakai with release script builds multiple builds of artifacts

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/cactus-build#67]
using the /release script in telenav-build causes multiple builds of artifacts to occur. after the 3rd build of Hadoop shaded jar, i aborted the attempt.

**Comment by timboudreau** [comment]
I don't really understand what is the bug here.  *Of course* the release script builds things multiple times - we designed it to do that.  What is surprising about the fact that it does?

**Comment by jonathanl-telenav** [comment]
closing this. the Hadoop stuff is a different repo now anyway
